---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: "12.6.0"
  environments_path: test/environments
  solo_rb:
    environment: kitchen

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[symfony::default]
    attributes:
